### ISSUE TITLE
Exception on Pay button without providing details

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/Braintree#6]
The following exception occurs if I press Pay button without filling in information:

```
System.InvalidOperationException: Can only be called on arrays.
   at Starcounter.Json.VerifyIsArray() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 17
   at Starcounter.Json.System.Collections.IEnumerable.GetEnumerator() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 478
   at BrainTreePaymentMethod.CustomerDataPage.Handle(Pay action) in D:\GitHub\handsoncode-apps\BraintreeDemoApp\BrainTreeApp\ViewModels\CustomerData\CustomerDataPage.json.cs:line 48
   at BrainTreePaymentMethod.CustomerDataPage.JsonByExample.Schema.<>c.<.ctor>b__0_27(Json pup, Input`1 input) in D:\GitHub\handsoncode-apps\BraintreeDemoApp\BrainTreeApp\obj\x64\Debug\ViewModels\CustomerData\CustomerDataPage.json.g.cs:line 0
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 225
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 247
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 105
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\TransactionManager.cs:line 449
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 27
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 629
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 470
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 59
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 handlerid, UInt32 groupId, WebSocket ws) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 661
HResult=-2146233079
```

Not clear, why would this code be here if it does nothing:

```cs
foreach (var inValidFields in isValidAddress)
{
	foreach(var fields in this.AddressErrors)
	{
		
	}
}
```

Found here: https://github.com/handsoncode-apps/BraintreeDemoApp/blob/master/BrainTreeApp/ViewModels/CustomerData/CustomerDataPage.json.cs#L46

**Comment by miyconst** [comment]
Actually, same exception happens if I fill in the data.

**Comment by warpech** [comment]
Perhaps because this file is empty? https://github.com/handsoncode-apps/BraintreeDemoApp/blob/master/BrainTreeApi/BrainTreeConfig.xml

I asked Jakub for account information by email.

**Comment by jakubklekota** [comment]
@miyconst it's fixed

**Comment by warpech** [comment]
Now, for me nothing happens when I click the "Pay" button.

Also, invalid fields that are still marked as invalid even after fixing them.

**Comment by jakubklekota** [comment]
Fixed

**Comment by warpech** [comment]
Works, closing
